name: "Lectito"
description: "A simple reading list"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "Maarten Steenhagen"
   email: "m.steenhagen.09@ucl.ac.uk"
