name: "Lectito"
description: "A simple reading list"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]

url: /lectito

author: "Maarten Steenhagen"
email: "m.steenhagen.09@ucl.ac.uk"
